In [69]:
import pandas as pd
import numpy as np

In [70]:
df_fb=pd.read_csv(r"..\data\01_facebook_ads.csv")
df_gg=pd.read_csv(r"..\data\02_google_ads.csv")
df_tt=pd.read_csv(r"..\data\03_tiktok_ads.csv")

In [71]:
df_fb.rename(columns={
    "spend":"cost",
    "ad_set_id":"ad_group_id",
    "ad_set_name":"ad_group_name"
    }, inplace=True)

df_gg.rename(columns={
    "avg_cpc":"cpc"
},inplace=True)

df_tt.rename(columns={
    "adgroup_id":"ad_group_id",
    "adgroup_name":"ad_group_name"
},inplace=True)

In [72]:
#FACEBOOK
df_fb["ctr"]=(
    df_fb["clicks"]/df_fb["impressions"]
    )

df_fb["cpc"]=(
    df_fb["cost"]/df_fb["clicks"]
)

df_fb["conversion_rate"]=(
    df_fb["conversions"]/df_fb["clicks"]
    )

df_fb["view_rate"]=(
       df_fb["video_views"]/df_fb["impressions"]
    )

#GOOGLE
df_gg["conversion_rate"]=(
    df_gg["conversions"]/df_gg["clicks"]
    )

#TIKTOK
df_tt["ctr"]=(
    df_tt["clicks"]/df_tt["impressions"]
    )

df_tt["cpc"] = (
    df_tt["cost"] / df_tt["clicks"]
    )

df_tt["conversion_rate"]=(
    df_tt["conversions"]/df_tt["clicks"]
    )

df_tt["view_rate"]=(
    df_tt["video_views"]/df_tt["impressions"]
    )

In [73]:
df_tt.head()

,date,campaign_id,campaign_name,ad_group_id,ad_group_name,impressions,clicks,cost,conversions,video_views,...,video_watch_50,video_watch_75,video_watch_100,likes,shares,comments,ctr,cpc,conversion_rate,view_rate
0,2024-01-01,tt_8001,Awareness_GenZ,ttad_9001,Dance_Challenge,234567,3456,456.7,34,198234,...,98234,67234,45234,8923,2345,567,0.014734,0.132147,0.009838,0.845106
1,2024-01-01,tt_8002,Conversion_Focus,ttad_9002,Product_Demo,123456,2345,678.9,67,89234,...,45234,34234,23456,4567,1234,234,0.018995,0.289510,0.028571,0.722800
2,2024-01-01,tt_8003,Traffic_Campaign,ttad_9003,Trending_Sounds,189234,2890,345.6,23,145678,...,89234,56789,34567,6789,1890,456,0.015272,0.119585,0.007958,0.769830
3,2024-01-02,tt_8001,Awareness_GenZ,ttad_9001,Dance_Challenge,245678,3678,478.9,36,207345,...,102345,70234,47234,9234,2456,589,0.014971,0.130207,0.009788,0.843971
4,2024-01-02,tt_8002,Conversion_Focus,ttad_9002,Product_Demo,134567,2567,712.3,71,95678,...,48234,36234,24567,4789,1345,245,0.019076,0.277483,0.027659,0.711006

In [74]:

def dummy_data(df,days):
    generated_data=[]
    for i in range(days):
        temp=df.copy()
        temp["date"]=(
            pd.to_datetime(temp["date"])
            + pd.Timedelta(days=i+1)
        )

        temp["impressions"]=(
            temp["impressions"]*np.random.uniform(0.92,1.08,len(temp))
        ).astype(int)

        temp["ctr"]=(
            temp["ctr"]*
            np.random.uniform(0.97,1.03,len(temp))
        ).round(4)

        temp["clicks"]=(
             temp["impressions"]*temp["ctr"]
        ).astype(int)

        temp["cpc"]=(
            temp["cpc"]*
            np.random.uniform(0.97,1.03,len(temp))
        ).round(2)

        temp["cost"]=(
            temp["clicks"]*temp["cpc"]
        ).astype(int)

        temp["conversion_rate"]=(
            temp["conversion_rate"]*
            np.random.uniform(0.95,1.05,len(temp))
        ).round(4)
        
        temp["conversions"]=(
            temp["clicks"]*temp["conversion_rate"]
        ).astype(int)

        if "video_views" in temp.columns:
            temp["view_rate"]=(
                temp["view_rate"]*
                np.random.uniform(0.95,1.05,len(temp))
            ).round(4)

            temp["video_views"]=(
                temp["impressions"]*temp["view_rate"]
            ).astype(int)

        if "reach" in temp.columns:
            temp["reach"]=(
                temp["impressions"]/
                np.random.uniform(1.10,1.30,len(temp))
            ).astype(int)

        if "frequency" in temp.columns and "reach" in temp.columns:
            temp["frequency"]=(
                temp["impressions"]/temp["reach"]
            ).round(2)
        
        if "engagement_rate" in temp.columns:
            temp["engagement_rate"]=(
                temp["engagement_rate"]*
                np.random.uniform(0.95,1.05,len(temp))
            ).round(4)

        generated_data.append(temp)

    return pd.concat(generated_data,ignore_index=True)

In [75]:
df_fb.head()

,date,campaign_id,campaign_name,ad_group_id,ad_group_name,impressions,clicks,cost,conversions,video_views,engagement_rate,reach,frequency,ctr,cpc,conversion_rate,view_rate
0,2024-01-01,fb_1001,Brand_Awareness_Q1,fbset_2001,Broad_Audience_18-35,45623,892,127.5,12,8234,0.0195,38234,1.19,0.019552,0.142937,0.013453,0.180479
1,2024-01-01,fb_1002,Conversions_Retargeting,fbset_2002,Cart_Abandoners,12456,567,215.8,34,1234,0.0455,9876,1.26,0.045520,0.380600,0.059965,0.099069
2,2024-01-01,fb_1003,Traffic_Drive_Jan,fbset_2003,Lookalike_Purchasers,34567,1234,189.9,23,4567,0.0357,28934,1.19,0.035699,0.153890,0.018639,0.132120
3,2024-01-02,fb_1001,Brand_Awareness_Q1,fbset_2001,Broad_Audience_18-35,42345,823,118.2,10,7890,0.0194,36789,1.15,0.019436,0.143621,0.012151,0.186327
4,2024-01-02,fb_1002,Conversions_Retargeting,fbset_2002,Cart_Abandoners,13678,623,234.5,38,1456,0.0455,10234,1.34,0.045548,0.376404,0.060995,0.106448

In [78]:
fb_dummy=dummy_data(df_fb,90)
gg_dummy=dummy_data(df_gg,90)
tt_dummy=dummy_data(df_tt,90)

In [79]:
fb_dummy.shape
gg_dummy.shape
tt_dummy.shape

(9900, 21)

In [80]:
fb_dummy["channel"]=np.random.choice(
    ["Paid Social","Organic"],
    size=len(fb_dummy),
    p=[0.85,0.15]
)

In [81]:
gg_dummy["channel"]=np.random.choice(
    ["Paid Search","Organic"],
    size=len(gg_dummy),
    p=[0.80,0.20]
)

In [82]:
tt_dummy["channel"]=np.random.choice(
    ["Paid Social"],
    size=len(tt_dummy)
)

In [83]:
fb_dummy["data_source"]=np.random.choice(
    ["Facebook Ads","LinkedIn Ads"],
    size=len(fb_dummy),
    p=[0.85,0.15]
)

gg_dummy["data_source"]=np.random.choice(
    ["Google Ads","Bing Ads"],
    size=len(gg_dummy),
    p=[0.75,0.25]
)

tt_dummy["data_source"]=np.random.choice(
    ["TikTok Ads","StackAdapt","Amazon Ad Server"],
    size=len(tt_dummy),
    p=[0.60,0.20,0.20]
)

In [84]:
fb_dummy.to_csv("../dummy_data/fb_dummy.csv",index=False)
gg_dummy.to_csv("../dummy_data/gg_dummy.csv",index=False)
tt_dummy.to_csv("../dummy_data/tt_dummy.csv",index=False)