In [10]:
import pandas as pd

In [29]:
df_fb=pd.read_csv(r"..\data\01_facebook_ads.csv")
df_gg=pd.read_csv(r"..\data\02_google_ads.csv")
df_tt=pd.read_csv(r"..\data\03_tiktok_ads.csv")

In [31]:
df_fb.info()
df_gg.info()
df_tt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             110 non-null    object
 1   campaign_id      110 non-null    object
 2   campaign_name    110 non-null    object
 3   ad_set_id        110 non-null    object
 4   ad_set_name      110 non-null    object
 5   impressions      110 non-null    int64
 6   clicks           110 non-null    int64
 7   spend            110 non-null    float64
 8   conversions      110 non-null    int64
 9   video_views      110 non-null    int64
 10  engagement_rate  110 non-null    float64
 11  reach            110 non-null    int64
 12  frequency        110 non-null    float64
dtypes: float64(3), int64(5), object(5)
memory usage: 11.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     110 non-null    object
 1   campaign_id              110 non-null    object
 2   campaign_name            110 non-null    object
 3   ad_group_id              110 non-null    object
 4   ad_group_name            110 non-null    object
 5   impressions              110 non-null    int64
 6   clicks                   110 non-null    int64
 7   cost                     110 non-null    float64
 8   conversions              110 non-null    int64
 9   conversion_value         110 non-null    float64
 10  ctr                      110 non-null    float64
 11  avg_cpc                  110 non-null    float64
 12  quality_score            110 non-null    int64
 13  search_impression_share  110 non-null    float64
dtypes: float64(5), int64(4), object(5)
memory usage: 12.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             110 non-null    object
 1   campaign_id      110 non-null    object
 2   campaign_name    110 non-null    object
 3   adgroup_id       110 non-null    object
 4   adgroup_name     110 non-null    object
 5   impressions      110 non-null    int64
 6   clicks           110 non-null    int64
 7   cost             110 non-null    float64
 8   conversions      110 non-null    int64
 9   video_views      110 non-null    int64
 10  video_watch_25   110 non-null    int64
 11  video_watch_50   110 non-null    int64
 12  video_watch_75   110 non-null    int64
 13  video_watch_100  110 non-null    int64
 14  likes            110 non-null    int64
 15  shares           110 non-null    int64
 16  comments         110 non-null    int64
dtypes: float64(1), int64(11), object(5)
memory usage: 14.7+ KB

In [35]:
print(df_fb.isnull().sum())
print(df_gg.isnull().sum())
print(df_tt.isnull().sum())

date               0
campaign_id        0
campaign_name      0
ad_set_id          0
ad_set_name        0
impressions        0
clicks             0
spend              0
conversions        0
video_views        0
engagement_rate    0
reach              0
frequency          0
dtype: int64
date                       0
campaign_id                0
campaign_name              0
ad_group_id                0
ad_group_name              0
impressions                0
clicks                     0
cost                       0
conversions                0
conversion_value           0
ctr                        0
avg_cpc                    0
quality_score              0
search_impression_share    0
dtype: int64
date               0
campaign_id        0
campaign_name      0
adgroup_id         0
adgroup_name       0
impressions        0
clicks             0
cost               0
conversions        0
video_views        0
video_watch_25     0
video_watch_50     0
video_watch_75     0
video_watch_100    0
likes              0
shares             0
comments           0
dtype: int64

In [43]:
df_fb.shape

(110, 13)

In [44]:
df_gg.shape

(110, 14)

In [45]:
df_tt.shape

(110, 17)

In [49]:
df_fb.describe()

,impressions,clicks,spend,conversions,video_views,engagement_rate,reach,frequency
count,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000
mean,41286.127273,808.172727,166.290909,21.772727,14659.127273,0.027135,34019.672727,1.223364
std,20448.876197,409.925768,56.550792,12.618364,18051.678156,0.016038,16991.307503,0.033463
min,10234.000000,223.000000,76.300000,4.000000,945.000000,0.003400,8234.000000,1.150000
25%,19567.000000,497.500000,119.550000,11.250000,2205.750000,0.019725,15789.500000,1.200000
50%,40345.000000,823.000000,163.800000,19.500000,6400.500000,0.028550,33345.000000,1.220000
75%,51650.250000,1114.500000,215.200000,32.000000,9567.000000,0.042275,43067.250000,1.240000
max,76890.000000,1567.000000,268.900000,47.000000,52345.000000,0.049600,62890.000000,1.340000

In [47]:
df_gg.describe()

,impressions,clicks,cost,conversions,conversion_value,ctr,avg_cpc,quality_score,search_impression_share
count,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000
mean,65668.581818,1250.818182,342.601818,38.345455,1917.272727,0.028135,0.318455,7.736364,0.604273
std,39926.311016,681.221612,170.794989,21.076286,1053.814312,0.018042,0.189974,0.925453,0.223362
min,21234.000000,412.000000,113.400000,11.000000,550.000000,0.003500,0.180000,6.000000,0.320000
25%,26872.500000,794.750000,209.200000,19.250000,962.500000,0.019500,0.190000,7.000000,0.420000
50%,48062.000000,1106.000000,283.250000,41.500000,2075.000000,0.032050,0.190000,8.000000,0.645000
75%,73456.000000,1498.000000,465.025000,56.500000,2825.000000,0.050300,0.280000,9.000000,0.890000
max,142345.000000,2567.000000,634.700000,75.000000,3750.000000,0.054400,0.660000,9.000000,0.940000

In [48]:
df_tt.describe()

,impressions,clicks,cost,conversions,video_views,video_watch_25,video_watch_50,video_watch_75,video_watch_100,likes,shares,comments
count,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000,110.000000
mean,260983.336364,4198.581818,675.151818,61.363636,210205.081818,164426.263636,120748.445455,83497.945455,54589.700000,10162.272727,2842.672727,703.772727
std,95121.798660,1446.714940,232.658181,29.057907,86309.277314,72132.535114,60811.855439,43171.939414,28833.783163,4715.898490,1395.494139,424.278657
min,112345.000000,2123.000000,345.600000,23.000000,82345.000000,61234.000000,41234.000000,31234.000000,21234.000000,4234.000000,1123.000000,212.000000
25%,190845.000000,3123.000000,475.350000,35.000000,147344.750000,113567.250000,90234.000000,57400.250000,34983.750000,6872.500000,1909.250000,461.500000
50%,245678.000000,3761.500000,606.650000,47.000000,199067.500000,154845.000000,109234.000000,72400.500000,46011.500000,8912.000000,2395.000000,578.000000
75%,309567.250000,4539.250000,862.325000,86.500000,254011.250000,197984.000000,130122.750000,85400.250000,55539.500000,11122.750000,2984.250000,714.500000
max,467890.000000,7623.000000,1189.400000,120.000000,401234.000000,323456.000000,258901.000000,184567.000000,122345.000000,20789.000000,6034.000000,1678.000000